"""empty message

Revision ID: ec7690c2fdc4
Revises: f8a26c0fd372
Create Date: 2019-12-23 19:30:16.064674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7690c2fdc4'
down_revision = 'f8a26c0fd372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'descrip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descrip', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
